development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: calendario_development
  pool: 5
  username: postgres
  password: 123

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: calendario_test
  pool: 5
  username: postgres
  password: 123

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: calendario_production
  pool: 5
  username: postgres
  password: 123
